apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qtrogr7ol-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qtrogr7ol-nodejs 
  name: qtrogr7ol-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qtrogr7ol-nodejs 
